### ISSUE TITLE
The CustomTool Jenkins plugin

### ISSUE THREAD

**Issue by jchoksi-whitbread** [zongoose/aws-ha-wordpress#2]
Should there be further instructions on configuring this plugin?

After installing the plugin and running the ```install.sh``` script and reloading Jenkins configuration from disk, I expected the plugin to be configured and ready to use. However, when the Jenkins job was run, it failed on the following lines:

```
// Get the Terraform tool.
def tfHome = tool name: &apos;Terraform&apos;, type: &apos;com.cloudbees.jenkins.plugins.customtools.CustomTool&apos;
env.PATH = &quot;${tfHome}:${env.PATH}&quot;
````

I had to comment them out to progress.

Note 1. I had the terraform binary on the system path.
Note 2. I had to remove the hard coded /tmp path in the following line as well:

```sh &quot;set +e; /tmp/terraform plan -out=plan.out -detailed-exitcode; echo \$? &gt; status&quot;```

**Comment by zongoose** [comment]
The terraform tool config should have been copied into the Jenkins folder by the install.sh script, however I see now that the existence check would cause this to fail as the Custom Tool xml file will exist even if no custom tools are configured. I will remove this from the install script and add instructions to the README to configure this through the Jenkins UI.
