### ISSUE TITLE
Hardcoded security group in the AWS Load Balancer terraform resource

### ISSUE THREAD

**Issue by jchoksi-whitbread** [zongoose/aws-ha-wordpress#4]
-	The terraform plan failed to apply due to the following security group not being found:

```sg-71465908```

We got the following error:

```
* aws_alb.hawordpress: Error creating Application Load Balancer: InvalidSecurityGroup: The security group 'sg-71465908' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidGroup.NotFound; Request ID: de6171dd-b22d-4e2e-8e76-f4e992f953e0)
    status code: 400, request id: 2d3d893b-52c2-11e7-b6b7-e9be1ce250ba
* aws_ecs_service.hawordpress: 1 error(s) occurred:
```

Please either provide details for the security group so that I may create our own one or amend the resource to remove the hard coded value.

**Comment by zongoose** [comment]
The hardcoded group was added while debugging a problem routing from the ALB to the ECS instances and refers to the default VPC security group. A new security group needs to be configured and both the ALB and the EC2 instances assigned to it. It should have an ingress rule that allows traffic from members of the group.
